const NICHES=["Lifestyle","Fashion","Beauty","Fitness","Travel","UGC / product","Brand ambassador"];
const MODES=[{id:"image",label:"Image"},{id:"edit",label:"Edit"},{id:"i2v",label:"Image → Video"},{id:"t2v",label:"Text → Video"}];
const RATIOS=["9:16","1:1","16:9","2:3","3:2"];
const QUALITIES=[{id:"low",label:"Low",image:5,edit:6},{id:"med",label:"Medium",image:22,edit:25},{id:"high",label:"High",image:80,edit:85}];
const DURS=[3,5,8,10];
const VIDEO_RATE={low:8,med:27,high:40};
const BLOCK=/\b(child|kids?|minor|underage|teen(ager)?s?|loli|preteen)\b/i;
const SIZE={"9:16":{w:768,h:1344},"1:1":{w:1024,h:1024},"16:9":{w:1344,h:768},"2:3":{w:832,h:1248},"3:2":{w:1248,h:832}};
const MIRA="Adult woman late 20s, olive-warm skin, dark brown wavy shoulder-length hair, hazel-green eyes, oval face, defined brows, natural makeup, photoreal skin texture. Not a celebrity.";
function demoShot(scene,seed){
  const p=MIRA+" "+scene+" Photoreal commercial photo, no text, no watermark.";
  const qs=new URLSearchParams({model:"flux",width:"640",height:"800",seed:String(seed),nologo:"true",safe:"true"});
  return "https://image.pollinations.ai/prompt/"+encodeURIComponent(p)+"?"+qs.toString();
}
const DEMO={portrait:demoShot("headshot, soft window light, beige wall",42042),street:demoShot("camel trench on a city street at golden hour",42043),beauty:demoShot("beauty close-up, dewy skin, beige seamless",42044),fitness:demoShot("sunrise run on a coastal boardwalk, athletic wear",42045),travel:demoShot("stone terrace at dusk, travel campaign",42046),product:demoShot("holding a frosted serum bottle, lifestyle UGC",42047),talk:demoShot("talking in a bright kitchen, mid speech",42048)};
const USES=[["Fashion model","Lookbooks without a day rate."],["Beauty","Texture shots that keep the same face."],["Fitness","Training content on any coast."],["Travel","The same talent in every city."],["Product UGC","Hands, hold, and reaction on-model."],["Brand ambassador","One face across every campaign."],["Headshots","Studio portraits on tap."],["Social model","9:16 and 1:1 from the same lock."]];
const state={page:"landing",credits:5,influencer:null,uploads:[],jobs:[],mode:"image",ratio:"9:16",quality:"low",duration:5,current:null,apiKey:"",imgModel:"flux",busy:false};
function load(){try{const raw=localStorage.getItem("nura.v2");if(raw){const s=JSON.parse(raw);state.credits=s.credits??5;state.influencer=s.influencer||null;state.jobs=(s.jobs||[]).slice(-40);state.apiKey=s.apiKey||"";state.imgModel=s.imgModel||"flux";}}catch(e){}}
function save(){const slimJobs=state.jobs.map(j=>({...j,src:(j.src&&j.src.startsWith("blob:"))?j.remote:j.src}));localStorage.setItem("nura.v2",JSON.stringify({credits:state.credits,influencer:state.influencer,jobs:slimJobs,apiKey:state.apiKey,imgModel:state.imgModel}));}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";clearTimeout(toast._id);toast._id=setTimeout(()=>t.style.display="none",2800);}
function setCredits(){document.getElementById("creditPill").textContent=state.credits+" cr";save();}
function go(page){state.page=page;document.querySelectorAll(".page").forEach(p=>p.classList.toggle("on",p.id===page));document.querySelectorAll("[data-nav]").forEach(b=>b.classList.toggle("on",b.dataset.nav===page));if(page==="studio")renderStudio();if(page==="library")renderLibrary();if(page==="settings"){document.getElementById("apiKey").value=state.apiKey;document.getElementById("imgModel").value=state.imgModel;}window.scrollTo(0,0);}
function startCreate(){go("create");}
function renderChips(el,items,current,onPick,labelFn){el.innerHTML=items.map(it=>{const id=typeof it==="string"?it:it.id;const label=labelFn?labelFn(it):(it.label||it);return `<button class="chip ${String(id)===String(current)?"on":""}" data-id="${id}">${label}</button>`;}).join("");el.querySelectorAll("button").forEach(b=>b.onclick=()=>onPick(b.dataset.id));}
function compressImage(file,max=720){return new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL("image/jpeg",0.72));};img.onerror=reject;img.src=url;});}
function initCreate(){const niches=document.getElementById("niches");state.niche=state.niche||"Lifestyle";renderChips(niches,NICHES,state.niche,id=>{state.niche=id;initCreate();});const slots=document.getElementById("slots");slots.innerHTML="";for(let i=0;i<10;i++){const d=document.createElement("div");d.className="slot";const img=state.uploads[i];d.innerHTML=img?`<img src="${img}" alt="">`:"+";const inp=document.createElement("input");inp.type="file";inp.accept="image/*";inp.onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>12*1024*1024){showCreateErr("Keep files under 12 MB.");return;}try{state.uploads[i]=await compressImage(f);initCreate();}catch{showCreateErr("Could not read that file.");}};d.appendChild(inp);slots.appendChild(d);}const n=state.uploads.filter(Boolean).length;document.getElementById("uploadCount").textContent=n+" / 10 · need 3 to build";}
function showCreateErr(m){const el=document.getElementById("createErr");el.textContent=m;el.classList.remove("hide");}
function useDemo(){state.influencer=demoInfluencer();save();go("studio");toast("Mira locked · seed "+state.influencer.seed);}
function demoInfluencer(){return{name:"Mira Vale",niche:"Lifestyle",appearance:MIRA,face:DEMO.portrait,refs:[DEMO.portrait,DEMO.street,DEMO.beauty,DEMO.fitness,DEMO.travel,DEMO.product],lock:88,seed:42042,demo:true};}
function buildInfluencer(){const name=document.getElementById("infName").value.trim()||"Untitled";const appearance=document.getElementById("appearance").value.trim();const n=state.uploads.filter(Boolean).length;const ok=document.getElementById("consent").checked;if(n<3){showCreateErr("Upload at least 3 photos of one adult.");return;}if(appearance.length<24){showCreateErr("Write a specific appearance lock.");return;}if(!ok){showCreateErr("Consent is required before a face lock.");return;}state.influencer={name,niche:state.niche||"Lifestyle",appearance,face:state.uploads.filter(Boolean)[0],refs:state.uploads.filter(Boolean).slice(0,8),lock:Math.min(90,50+n*4),seed:10000+Math.abs(hash(name+"|"+appearance))%80000,demo:false};save();go("studio");toast("Face card locked · seed "+state.influencer.seed);}
function currentCost(){const q=QUALITIES.find(x=>x.id===state.quality);if(state.mode==="image")return q.image;if(state.mode==="edit")return q.edit;const clip=VIDEO_RATE[state.quality]*state.duration;if(state.mode==="t2v")return clip+(state.quality==="low"?5:22);return clip;}
function updateCost(){const c=currentCost();document.getElementById("genBtn").textContent=state.busy?"Working…":`Generate · ${c} cr`;document.getElementById("genBtn").classList.toggle("busy",state.busy);const kind=state.mode.includes("v")?`${state.duration}s ${state.quality} clip`:`${QUALITIES.find(x=>x.id===state.quality).label} ${state.mode}`;document.getElementById("costLine").textContent=`${kind} · ${c} credits · ${state.ratio}`;document.getElementById("videoOpts").classList.toggle("hide",!state.mode.includes("v"));}
function renderStudio(){if(!state.influencer)state.influencer=demoInfluencer();const inf=state.influencer;document.getElementById("studioTitle").textContent=inf.name+" · Studio";document.getElementById("faceImg").src=inf.face;document.getElementById("faceName").textContent=inf.name;document.getElementById("faceMeta").textContent=`${inf.niche} · lock ${inf.lock}% · seed ${inf.seed}`;document.getElementById("faceRefs").innerHTML=(inf.refs||[]).slice(0,8).map(s=>`<img src="${s}" alt="">`).join("");document.getElementById("lockNote").textContent=(inf.appearance||"").slice(0,180);renderChips(document.getElementById("modes"),MODES,state.mode,id=>{state.mode=id;renderStudio();});renderChips(document.getElementById("ratios"),RATIOS,state.ratio,id=>{state.ratio=id;renderStudio();});renderChips(document.getElementById("qualities"),QUALITIES,state.quality,id=>{state.quality=id;renderStudio();},q=>`${q.label} ${state.mode==="edit"?q.edit:q.image}`);renderChips(document.getElementById("durations"),DURS.map(String),String(state.duration),id=>{state.duration=+id;renderStudio();},d=>d+"s");document.getElementById("promptLabel").textContent=state.mode==="edit"?"EDIT INSTRUCTION":state.mode==="i2v"?"MOTION + OPTIONAL LINE IN QUOTES":"SCENE";updateCost();renderGallery(document.getElementById("gallery"),state.jobs.slice().reverse());}
function hash(s){let h=0;for(let i=0;i<String(s).length;i++)h=((h<<5)-h)+s.charCodeAt(i)|0;return h;}
function buildPrompt(userText,mode){const inf=state.influencer||demoInfluencer();const quote=(userText.match(/"([^"]+)"/)||[])[1];const scene=userText.replace(/"[^"]*"/g,"").trim();const speak=quote?` Mouth mid-speech as if saying: "${quote}".`:"";const identity=`Photorealistic photograph of ONE specific adult person only. Identity lock (must match exactly): ${inf.appearance}. Same unique face, bone structure, eye color, nose, mouth, skin tone and hair in every frame.`;if(mode==="edit")return `${identity} Apply this change while keeping the same person: ${scene||userText}. No extra people, no text overlay, no watermark.`;if(mode==="i2v"||mode==="t2v")return `${identity} Cinematic still that can be animated. ${scene}.${speak} Natural motion pose, ${state.ratio} frame, no text, no watermark.`;return `${identity} Scene: ${scene}. ${state.ratio} composition, commercial photography, sharp eyes, natural lighting, no text, no watermark.`;}
function imageUrl(prompt,seed,w,h){const model=(state.imgModel||"flux").trim();const qs=new URLSearchParams({model,width:String(w),height:String(h),seed:String(seed),nologo:"true",safe:"true",enhance:state.quality==="high"?"true":"false",private:"true"});return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?${qs.toString()}`;}
function waitForImage(url,timeoutMs){return new Promise((resolve,reject)=>{const img=new Image();const t=setTimeout(()=>{img.src="";reject(new Error("Timed out waiting for the model"));},timeoutMs);img.onload=()=>{clearTimeout(t);resolve(url);};img.onerror=()=>{clearTimeout(t);reject(new Error("Model rejected the job or the queue is full"));};img.src=url+(url.includes("?")?"&":"?")+"ts="+Date.now();});}
async function runStill(prompt,seed){const dim=SIZE[state.ratio]||SIZE["9:16"];const scale=state.quality==="low"?0.75:state.quality==="high"?1:0.9;const w=Math.round(dim.w*scale);const h=Math.round(dim.h*scale);const url=imageUrl(prompt,seed,w,h);let lastErr;for(let attempt=0;attempt<4;attempt++){try{await waitForImage(url,90000);return url;}catch(err){lastErr=err;await new Promise(r=>setTimeout(r,1800*(attempt+1)));}}throw lastErr||new Error("Generation failed");}
async function runVideo(prompt,stillUrl){if(!state.apiKey)throw new Error("Video needs a Pollinations API key (Settings). Still generated instead.");const duration=Math.min(10,Math.max(4,Number(state.duration)||5));const qs=new URLSearchParams({model:"bytedance/seedance-2.0-mini",duration:String(duration),aspectRatio:state.ratio||"9:16",nologo:"true",private:"true",audio:"true"});if(stillUrl)qs.set("image[0]",stillUrl);const url=`https://gen.pollinations.ai/video/${encodeURIComponent(prompt)}?${qs.toString()}`;const res=await fetch(url,{headers:{Authorization:"Bearer "+state.apiKey}});if(!res.ok){const body=await res.text();throw new Error("Video API "+res.status+": "+body.slice(0,180));}const blob=await res.blob();if(!blob.type.startsWith("video")&&!blob.type.startsWith("image"))throw new Error("Video endpoint returned "+blob.type);return{url:URL.createObjectURL(blob),type:blob.type};}
function surprise(){const samples=["Wearing a camel trench on a stone terrace at dusk, travel campaign","Holding a frosted serum bottle, beauty close-up, beige seamless","Denim jacket on a city crosswalk at golden hour","Sunrise run on a coastal boardwalk, athletic wear","Cafe table, holding a matte black product case, lifestyle UGC","Talking in a bright kitchen. \"This is the only serum I pack.\""];document.getElementById("prompt").value=samples[Math.floor(Math.random()*samples.length)];}
async function generate(){if(state.busy){toast("One job at a time on the free queue.");return;}const raw=document.getElementById("prompt").value.trim();if(BLOCK.test(raw)){toast("Prompt blocked. No charge.");return;}if(!raw&&state.mode!=="i2v"){toast("Describe the shot.");return;}const cost=currentCost();if(state.credits<cost){toast("Not enough credits.");go("pricing");return;}const id="j"+Date.now();const prompt=buildPrompt(raw,state.mode);const inf=state.influencer||demoInfluencer();const job={id,status:"queued",prompt:raw||"locked identity",fullPrompt:prompt,mode:state.mode,ratio:state.ratio,quality:state.quality,duration:state.duration,src:"",remote:"",title:inf.name+" · "+state.mode,video:state.mode.includes("v"),created:Date.now(),cost};state.jobs.push(job);state.credits-=cost;state.busy=true;setCredits();renderStudio();try{const still=await runStill(prompt,inf.seed);job.remote=still;job.src=still;if(job.video){try{const vid=await runVideo(prompt,still);job.src=vid.url;job.kind=vid.type;job.title+=" · motion";}catch(ve){job.video=true;job.note=String(ve.message||ve);toast(job.note);}}job.status="done";toast("Ready · "+job.title);}catch(err){job.status="fail";job.error=String(err.message||err);state.credits+=cost;setCredits();toast("Failed, credits refunded. "+job.error);}finally{state.busy=false;save();if(state.page==="studio")renderStudio();else updateCost();}}
function renderGallery(el,jobs){if(!jobs.length){el.innerHTML=`<div class="muted" style="padding:20px">No jobs yet. Generate a still — this hits a live image model.</div>`;return;}el.innerHTML=jobs.map(j=>{if(j.status==="queued")return `<article class="card"><div class="spin">Generating · ${j.quality}<br><span class="muted">${j.mode} · ${j.ratio}<br>free queue, can take 15–60s</span></div></article>`;if(j.status==="fail")return `<article class="card"><div class="spin" style="color:var(--bad)">Failed<br><span class="muted">${escapeHtml(j.error||"")}</span></div></article>`;const media=(j.kind||"").startsWith("video")?`<video src="${j.src}" muted autoplay loop playsinline style="width:100%;height:240px;object-fit:cover"></video>`:`<img src="${j.src}" alt="">`;return `<article class="card ${j.video&&!(j.kind||"").startsWith("video")?"video-frame":""}" onclick='openLb(${JSON.stringify(j.id)})'><span class="lbl">${j.video?"VIDEO · "+j.duration+"s":j.ratio+" · "+j.quality.toUpperCase()}</span>${media}<div class="cap">${escapeHtml(j.prompt).slice(0,80)}</div></article>`;}).join("");}
function renderLibrary(){renderGallery(document.getElementById("libGallery"),state.jobs.filter(j=>j.status==="done").reverse());}
function clearLibrary(){state.jobs=[];save();renderLibrary();toast("Library cleared");}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">","\"":""","'":"&#39;"}[c]));}
function openLb(id){const j=state.jobs.find(x=>x.id===id);if(!j)return;state.current=j;document.getElementById("lbImg").src=j.src;document.getElementById("lbCap").textContent=`${j.title} · ${j.mode} · ${j.ratio} · ${j.cost} cr${j.note?" · "+j.note:""}`;document.getElementById("lb").classList.add("on");}
function closeLb(){document.getElementById("lb").classList.remove("on");}
async function downloadCurrent(){if(!state.current)return;try{const res=await fetch(state.current.src);const blob=await res.blob();const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="nura-"+state.current.id+".jpg";a.click();}catch{window.open(state.current.src,"_blank");}}
function animateCurrent(){if(!state.current)return;state.mode="i2v";document.getElementById("prompt").value=state.current.prompt;closeLb();go("studio");toast("Motion mode armed");}
function editCurrent(){if(!state.current)return;state.mode="edit";document.getElementById("prompt").value="Change the outfit and background, keep the same face. "+state.current.prompt;closeLb();go("studio");}
function grantCredits(n,plan){state.credits+=n;setCredits();toast(plan+" credits added");go("studio");}
function saveSettings(){state.apiKey=document.getElementById("apiKey").value.trim();state.imgModel=document.getElementById("imgModel").value.trim()||"flux";save();document.getElementById("settingsMsg").textContent=state.apiKey?"Key saved in this browser.":"Saved. Running anonymous Flux.";}
async function testProvider(){document.getElementById("settingsMsg").textContent="Testing a 640px still…";try{const url=imageUrl("photoreal test still of a ceramic cup on oak table, no people",1,640,640);await waitForImage(url,60000);document.getElementById("settingsMsg").textContent="Provider OK.";}catch(e){document.getElementById("settingsMsg").textContent="Test failed: "+e.message;}}
function boot(){load();setCredits();document.querySelectorAll("[data-demo]").forEach(el=>{el.src=DEMO[el.dataset.demo]||DEMO.portrait;});document.getElementById("strip").innerHTML=[DEMO.portrait,DEMO.street,DEMO.beauty,DEMO.fitness,DEMO.travel,DEMO.product,DEMO.talk].map(s=>`<img src="${s}" alt="">`).join("");document.getElementById("useGrid").innerHTML=USES.map(([t,d])=>`<article class="feat"><h3>${t}</h3><p class="muted">${d}</p></article>`).join("");initCreate();}
boot();
